name: listing S3 Buckets

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    list_s3_buckets:
        runs-on: ubuntu-latest
        steps:
            - name: Set up AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.IAM_ROLE}}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: List S3 Buckets
              env:
                  AWS_REGION: ${{ secrets.AWS_REGION }}
              run: |
                  echo "Listing S3 Buckets"
                  aws s3 ls
